name: inventario-it-prod

services:
  inventario:
    build: .
    container_name: inventario-it
    ports:
      - "3131:8000"
    volumes:
      - ./backend/it_inventario.db:/app/backend/it_inventario.db
      - ./backend/static:/app/backend/static
    restart: unless-stopped
